spring.application.name=crud

spring.mvc.hiddenmethod.filter.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/todoDB
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
